# Generated by Django 3.2.16 on 2022-12-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='farmgroup',
            table='farm_groups',
        ),
    ]
